name: Quality Requirements Satisfaction

on: [push, pull_request]

jobs:
  maintainability:
    runs-on: ubuntu-latest
    name: Running pytest, coverage reports
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: pytesting
        run: |
          pytest -s --cov=app/ test/
          pytest -s --cov=app/ --cov-branch test/
          coverage report --fail-under=60

  reliability:
    runs-on: ubuntu-latest
    name: Linting with flake8 and ruff
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: flake8 Lint
        uses: py-actions/flake8@v2

      - name: Ruff Lint
      - uses: astral-sh/ruff-action@v3
  
  security:
    runs-on: ubuntu-latest
    name: Security checks via bandit, snyk
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Run Bandit
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/bandit/master/pipeline.sh)

      - name: Run Snyk for only severe vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # performance:
  #   runs-on: ubuntu-latest
  #   name: locust usage

  deploy:
    runs-on: ubuntu-latest
    needs: [pytest, lint, security]
    steps:
      - run: echo "This is where Deployment should happen"


